name: Main Branch Commit

on:
  push:
    branches: [ 'main' ]
  schedule:
    # At 5:30 am on the 1st and 15th day of the month (every two weeks)
    - cron: '30 5 1,15 * *'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_USERNAME: ${{ vars.GH_USERNAME }}
  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
  HOST_NAME: ${{ vars.HOST_NAME }}
  CUSTOM_URI_SCHEME: ${{ vars.CUSTOM_URI_SCHEME }}

  JAVA_VERSION: '17'
  RUBY_VERSION: '3.1'
  CURRENT_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  build_and_tag:
    name: Build and Tag
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - name: Checkout Project
        uses: actions/checkout@v4

      # Set Ruby version and Cache RubyGem dependencies
      - name: Cache RubyGem Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      # Ensure correct Java version is installed
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # Generate build number based on Git tag
      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ env.GITHUB_TOKEN }}

      # Setup Git user to make Fastlane capable to create Git tags
      - uses: fregante/setup-git-user@v2

      # Build the Android app
      - name: Run Fastlane
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'main'
          options: |
            {
              "host_name": "${{ env.HOST_NAME }}",
              "custom_uri_scheme": "${{ env.CUSTOM_URI_SCHEME }}"
            }
